//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fstCopy_Proj5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ad
    {
        public int id { get; set; }
        public string nationalId { get; set; }
        public string data { get; set; }
        public string listId { get; set; }
        public string partyName { get; set; }
        public string electionArea { get; set; }
        public string description { get; set; }
        public string URL { get; set; }
        public string status { get; set; }
    }
}
