//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fstCopy_Proj5.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DATE
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> startDateNominate { get; set; }
        public Nullable<System.DateTime> EndDateNominate { get; set; }
        public Nullable<System.DateTime> startDateOfElection { get; set; }
        public Nullable<System.DateTime> EndDateOfElection { get; set; }
    }
}
